hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bd579053a3e8fb35c2d9146eb31d214c3276a270d3b032f4b087e8042d2ce20d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "a1e7268a9c90dd490f8cea23af5526ff22e8ddde2475afab7946e3af82b05e49"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "851741ce6061b1914a07e3a88950e44b06c251c2eb4c11d462423890695f397c"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "066bcf27ce64eeaeb8e595f3768743c02e3a5fa2f7338357a523b8a72f0814df"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "33cee9c3a8101ab66a547729c3316607f9aa46a83a1f224f32a2114022db5f0a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "a0f2e11e55aa98b13ca469e8cee71d38a16a2ed0fba99b95fb0664adfc93e838"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "ac7153ccd646c14f801c2fe70c50eec5633db769ff1837f5ae00f45ff78a16e4"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
hash = "2b7c95d31393c08887de983ec5895ded70270f480463917939b689d4ff4e1a12"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
hash = "8530bb8ab9c96826845acbebf96a0fd136ddacd68e3834c18d717b81b690aca1"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "7d227ef90b1918ceb348ade235a5d17c7894acbf387575e96c08920a5bad1bbb"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "2c65b7ed826a2d147f0eb4788152b9f1ae878e0df102af58a9ea23ebd1c48f04"
metafile = true

[[files]]
file = "mods/create-power-loader-fabric.pw.toml"
hash = "bf8514a56af755dd22d7ef3994e0c6e33d4db963eea2688fdbe466f998e123b2"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "b79bc9976d5958f4b88ca23575e0d0dc677a2b06931108f6f7bc3fd3e46bb22c"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
hash = "96b0da15913458b2d1aa9ba1f95bb55ea34867625e0018f4c765562dab055313"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "e9ba6ffa1109ca957fef061ef4b41a46300b3cfb382ef4ae24f96c54309fd31f"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "2748a91387d8bd583894ed2271eea4f3889095ebb0c72372b79e3a4878110710"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c3bf7d6d25260b023f8cd2906527bf2ddfe36eb7929894ac0ae6d61abe2328cd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c7763ceed9929d3364030c01a4602628ebf46a028d55e7dd06f5aeb6280d36a3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "bb9a29a48b27e7abc0799d4393240ae2cdcf7d64341c9a63347769173f8bda2e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d5db994a9bdf835c0bda791ef6a0eed315f77a1dc5bab1ce04003a9ab5a4b01f"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "1c54a2d4aa370e2bcb086caad15e4fa36bdd98e825ddda5672bbdcd23ad477df"
metafile = true

[[files]]
file = "mods/ftb-ultimine-fabric.pw.toml"
hash = "dfa3b6fcff71eda68630dbadf8e23d28713e8ee45fd26a4b1df53a98c804575c"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "0e99c9b4a524d9cb74553f7b3ed331081031fef9d3c0c437f3734fbd9a350a2d"
metafile = true

[[files]]
file = "mods/herdspanic.pw.toml"
hash = "a4540dd8807f53182939edae5f114e801097433370a3b11a3c19a5e940d7b6c1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2e441b5e21e8db1cd9102216ce4b8d1a25d77a026182e00f6324aadda402f715"
metafile = true

[[files]]
file = "mods/immersivethunder.pw.toml"
hash = "1e7626658f151f660110a788c0e3771f08a023992a62c38aacb272fd9559dd94"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "3d41978dc3fd1d7b7eebe51a7c04e49707e7e7c66f764a1bed0cc214e4032995"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "956298b1bbab6d8bfb5074b169d8d24d04d688182edf8af885bbefc6cc1d9c27"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "4b2d106ce00d09612a66ced11538304eedc540267a285976da54da8f2f624eb2"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "dbe91bc9bc5339ca6664fa5e367335eeb0c82df6912be34f3f7b1e6dca3749bb"
metafile = true

[[files]]
file = "mods/just-mob-heads.pw.toml"
hash = "c7446d82504c76ff0820702a634530f741a0224aaa1fd1b17c80e1bda70baa7c"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b96bbf63944073e63e84ecbad6c00263f794c8be9b3623d0e62af23328ff4e66"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "470d30cd94b769b646f714432ba4cd01969910f6016957a6b218d2d2900d914c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "8c8a415665b41e96e7afd7503a94fa58998677801eab82931112314459723ffd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "928f468ee559de65f53d3758c1cd3f98ef2e0a7a9aa360355ef5114f565606cf"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "0e4b66acb56a69961e0324eb902df9f490b8681b3d3f99ac3f96bb1b55ad1ba9"
metafile = true

[[files]]
file = "mods/our-villager-discounts.pw.toml"
hash = "d4468887af2c277449fecba6323f41f2a911258617df59b1d9f1ab12ead3d6d8"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "974fc9a82d211049b57b4d9dd0b7bb2e203d5a9b88d20a3f8ce2c3a16ee4426b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/simple-animated-guns-(fan-retextured).pw.toml"
hash = "4eeb57bc412b552170fe2c13711c7d4df299f0a00f5e389846b5835b4b00624c"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "d7062507251f577355a3c3e4fd3bc33ea9ac0e74ad0da2c8f0eb6c9b9c182b99"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "6b7e9ed619297a29eb6db95f860734144876aa68922de63a05409b65ad8bd163"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "350cd01b8b55cea244c2b0ea7bb3c9a6ba873cea4701528c62101c63af6b027a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "5897110ecb150ac1a8b8160e58f37cf135d93a57ffdb0328354e408c6d6270b8"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "de212d0f51e294cdee8988506672abcb4f87ca0fd329d1ecdb4b1bb2aa4c252d"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "fc4ed216a79a9a26afffd05b3d9dcc3bea003cd2e3ed7a4b78cd51201e72b3a3"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "4ca11e8b2f08020232bce98e6329e0831b95c9f4be962126ab865aee503a9724"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fadb1aaba6c522a2cfccbc04366ebbf49bcfc336ea1f96f3ff59781ce8b94d2d"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "1dd540094372fc739857d45308c7bee815d7e0e77b9f59a0aecf2f60d37dbf7c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "88121fbabab3563f8dbb84a32347c753d23eec466c1df3225570cdb42e251029"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "95940b5fc72e8df82ab3adb72b43d10a37e6d926fbb37c405c9fe50bda27a991"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "7dd536d000999274472fa6762bcd49deaeb301fd0889c32723c1129db2400561"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "0958d9f10d0e8fb282b8e684b05b37b29aca826d48deeec3e44171857c99aca5"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "c360a4aef0ce719d385529002ba157a731d572b73cefb573c763d71d54039078"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "cf708ff146f867df2153b3f27482e80769c7032b10037e4a752d31fbb5668eaf"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "8bc20a4cf22bdd4406a64126647cfe3c704e80a3197031c9154032905a276705"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f23d28e95b21a9655e615390a560bc66f3cb87610ac38cd9d849129d0600a766"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "b2af03e504a1827f2f6fc09597e7d51f4ecd64ab1ebb329a9eb9ffb98372673a"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "d201155cab7c2a2cf940d91f240be769ac12046c2fc6a0774e225a8e51423ed0"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "8ff523efcbaf14d3d6ab2b845360f6207029ec30e56b4f8d9f3f478d1deb2fc9"
metafile = true
